### ISSUE TITLE
add ability to color markers

### ISSUE THREAD

**Issue by rickyars** [JoranBeaufort/Leaflet.windbarb#1]
First, let me say that this is great. I got it working with R and leaflet without too much trouble and I'm pretty excited. Now I would just like to be able to change the color of the marker. 

I'm an R programmer, no javascript experience, but I think I see where I can change the color. Now say I wanted to change the color based on some other value/attribute in my data instead of having the color hard-coded. That would be pretty cool. 

So, do you think we could get the ability to pass the color in as an option?

**Comment by spatialsparks** [comment]
Hey @rickyars 
Thank you for using this plugin and nice to hear that you got it working! I have not been very active of late because I just cannot find the time.

But changing the colour should be easy: create new option variables with default values, and add the colour to the SVG circle or the lines, using conditions if needed. At the moment I have no time to look into this, but will leave it open and have a look when I find time and get back to you.

But honestly, I think trying yourself might be faster :)
Cheers

**Comment by rickyars** [comment]
Thanks for the reply. I'm sure I can figure it out. I was mostly posting as a "feature request." If I make something I'm proud of, I'll send you a pull request.

**Comment by spatialsparks** [comment]
That sounds great! If it works send me a link to your code or make a pull request. Doesn't have to be perfect, this plugin is a long way from perfect or efficient anyhow ;) Looking forward to seeing your idea!
Cheers
