### ISSUE TITLE
Awesome project

### ISSUE THREAD

**Issue by jaka87** [JoranBeaufort/Leaflet.windbarb#4]
Hi.

I just want to say I really like your work and your script works like a charm. I did some minor changes and use it for my website that shows data for windsurfers and kiters.

Here is the live version
http://vetercek.com/mapa/

Many thanks,
Jaka

**Comment by spatialsparks** [comment]
Hi Jaka!

Thank you so much, very cool project you have there! I am also windsurfer and also initially created this plugin to better visualise the current wind states at a lake where I go surfing :) If you want, give me email address so you can give me a few cool tips on windsurf spots in the area of your map, maybe we will check out the spot one day instead of going to the south of France ;) 
Hang Loose

**Comment by jaka87** [comment]
Hi Manuel.

Sorry for the long reply. You can deferentially contact me with info[at]
vetercek.com if you need any tips regarding local surfing spots.

Best regards,
Jaka

**Comment by spatialsparks** [comment]
Hi there! Nice, thanks! Will definitely contact you if Im coming into that area 👍
